name: GMRT Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-streamlit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
        echo "MEXC_API_KEY=${{ secrets.MEXC_API_KEY }}" >> .env
        echo "MEXC_SECRET_KEY=${{ secrets.MEXC_SECRET_KEY }}" >> .env
    
    - name: Deploy Streamlit app
      uses: streamlit/streamlit-deploy@v1
      with:
        app-name: gmrt-tracker
        s3-bucket-name: ${{ secrets.AWS_S3_BUCKET }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
        echo "MEXC_API_KEY=${{ secrets.MEXC_API_KEY }}" >> .env
        echo "MEXC_SECRET_KEY=${{ secrets.MEXC_SECRET_KEY }}" >> .env
    
    - name: Run bot
      run: python whale_tracker.py
