name: GMRT Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
        echo "MEXC_API_KEY=${{ secrets.MEXC_API_KEY }}" >> .env
        echo "MEXC_SECRET_KEY=${{ secrets.MEXC_SECRET_KEY }}" >> .env
    
    - name: Run bots
      run: |
        # Start multi_exchange_tracker in background
        python multi_exchange_tracker.py &
        # Start volume_visualizer in background
        python volume_visualizer.py &
        # Wait for data collection (30 seconds)
        sleep 30
        # Kill background processes
        pkill -f "python"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: true
