name: GMRT Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]  # Also run on pushes to main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-bots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
        echo "MEXC_API_KEY=${{ secrets.MEXC_API_KEY }}" >> .env
        echo "MEXC_SECRET_KEY=${{ secrets.MEXC_SECRET_KEY }}" >> .env
    
    - name: Ensure docs directory exists
      run: mkdir -p docs
    
    - name: Run bots
      run: |
        # Start multi_exchange_tracker in background
        python multi_exchange_tracker.py &
        # Start volume_visualizer in background
        python volume_visualizer.py &
        # Wait for data collection (30 seconds)
        sleep 30
        # Kill background processes
        pkill -f "python"
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
